/*
 * Cyla App API
 *
 * API for the period tracking app 'Cyla'
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package server

import (
	"context"
)

// UserApiService is a service that implents the logic for the UserApiServicer
// This service should implement the business logic for every endpoint for the UserApi API.
// Include any external packages or services that will be required by this service.
type UserApiService struct {
}

// NewUserApiService creates a default api service
func NewUserApiService() UserApiServicer {
	return &UserApiService{}
}

// CreateUser -
func (s *UserApiService) CreateUser(ctx context.Context, user User) (ImplResponse, error) {
	ret, err := DBConnection.CreateUser(ctx, user)
	return httpResponseWithBody(ret, err)
}

// GetRestoreData -
func (s *UserApiService) GetRestoreData(ctx context.Context, userId string) (ImplResponse, error) {
	ret, err := DBConnection.GetRestoreData(ctx, userId)
	return httpResponseWithBody(ret, err)
}

// GetUserById -
func (s *UserApiService) GetUserById(ctx context.Context, userId string) (ImplResponse, error) {
	ret, err := DBConnection.GetUserById(ctx, userId)
	return httpResponseWithBody(ret, err)
}

// UpdateUser -
func (s *UserApiService) UpdateUser(ctx context.Context, userId string, user User) (ImplResponse, error) {
	err := DBConnection.UpdateUser(ctx, userId, user)
	return httpResponse(err)
}
