version: "3.8"

services:
  redis:
    container_name: redis
    image: "redis:6.0.9"
    command: redis-server --requirepass "${REDIS_PASSWORD}" --appendonly yes
    ports:
      - "6379:6379"
    environment:
      - REDIS_REPLICATION_MODE=master
    volumes:
    - ./store:/data
    - ./backend/resources:/tmp/scripts
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile-cosmtrek-air
    working_dir: '/go/src/github.com/cyla-app/cyla-app'
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/go/src/github.com/cyla-app/cyla-app
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - CYLA_ENV=${CYLA_ENV}
