/*
 * Cyla App API
 *
 * API for the period tracking app 'Cyla'
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"
	"net/http"

	server "github.com/cyla-app/cyla-app/server"
)

func main() {
	log.Printf("Server started")
    // Initialize DB connection as global variable
    server.InitializeDBConnection()

	DayApiService := server.NewDayApiService()
	DayApiController := server.NewDayApiController(DayApiService)

	UserApiService := server.NewUserApiService()
	UserApiController := server.NewUserApiController(UserApiService)

	router := server.NewRouter(DayApiController, UserApiController)

	log.Fatal(http.ListenAndServe(":5000", router))
}
