openapi: 3.0.3
info:
  description: ""
  version: 0.1.0
  title: "Cyla App Frontend Types"
servers: [ ]
paths: { }
components:
  schemas:
    Day:
      type: object
      description: A Day entry
      properties:
        temperature:
          $ref: "#/components/schemas/Temperature"
        bleeding:
          $ref: "#/components/schemas/Bleeding"
        mucus:
          $ref: "#/components/schemas/Mucus"
        cervix:
          $ref: "#/components/schemas/Cervix"
        #sexualActivity:
        #  type: array
        #  items:
        #    $ref: "#/components/schemas/SexualActivity"
        #sexualDesire:
        #  $ref: "#/components/schemas/SexualDesire"
        #pain:
        #  $ref: "#/components/schemas/Pain"
        #mood:
        #  $ref: "#/components/schemas/Mood"
        #ovulationTest:
        #  $ref: "#/components/schemas/OvulationTest"
        excludeReason:
          $ref: "#/components/schemas/ExcludeReason"
    Bleeding:
      type: object
      description: Bleeding information for a day
      properties:
        strength:
          type: string
          enum: [ 'none', 'weak', 'medium', 'strong' ]
      required:
        - strength
    Temperature:
      type: object
      description: Temperature information for a day
      properties:
        value:
          type: number
          format: float
          multipleOf: 0.01
        timestamp:
          type: string
          format: date-time
        note:
          type: string
          maxLength: 500
      required:
        - value
        - timestamp
    Mucus:
      type: object
      description: Cervical Mucus information for a day
      properties:
        feeling:
          type: string
          enum: [ none, dry, wet, slippery ]
        texture:
          type: string
          enum: [ none, creamy, egg white ]
      required:
        - feeling
        - texture
    Cervix:
      type: object
      description: Cervix information for a day
      properties:
        opening:
          type: string
          enum: [closed, medium, raised]
        firmness:
          type: string
          enum: [firm, medium, soft]
        position:
          type: string
          enum: [low, medium, high]
      required:
        - opening
        - firmness
        - position
    #    OvulationTest:
    #      type: object
    #      description: Result of an ovulation test for a day
    #      properties:
    #        result:
    #          type: boolean
    #    Mood:
    #      type: object
    #      description: Mood information for a day
    #      properties:
    #        type:
    #          type: string
    #          enum: [happy, confident, calm, energetic, excited, PMS, mood swings, irritable, anxious, stressed, tired, sensitive, numb, sad, angry]
    #    Pain:
    #      type: object
    #      description: Pain information for a day
    #      properties:
    #        type:
    #          type: string
    #          enum: [cramps, ovulation pain, headache, backache, nausea, tender breasts, migraine, other]
    #    SexualDesire:
    #      type: object
    #      description: Sexual desire information for a day
    #      properties:
    #        intensity:
    #          type: integer
    #          minimum: 0
    #          maximum: 10
    #    SexualActivity:
    #      type: object
    #      description: Information about a sexual activity
    #      properties:
    #        contraceptives:
    #          type: string
    #          enum: [ none, condom, female condom, pill, ring, patch, hormonal IUD, copper IUD, chemical, diaphragm, implant ]
    ExcludeReason:
      type: string
      enum: [ none, sick, hungover, sleep ]
