templateDir: /local/openapi/go-server_templates
additionalProperties:
  serverPort: 5000
  sourceFolder: server
packageName: server
importMappings:
  # We import the mappings for the custom alis types as a mini-hack so the generator doesn't consider them simply strings.
  EncryptedAttribute: server.EncryptedAttribute
  DayDate: server.DayDate
files:
  custom_templates/custom_types.mustache:
    folder: server
    templateType: SupportingFiles
    destinationFilename: model_custom_types.go
  custom_templates/http_error.mustache:
    folder: server
    templateType: SupportingFiles
    destinationFilename: http_error.go
  custom_templates/response.mustache:
    folder: server
    templateType: SupportingFiles
    destinationFilename: response.go
  custom_templates/db_connector.mustache:
    folder: server
    templateType: SupportingFiles
    destinationFilename: db_connector.go
