openapi: 3.0.3
info:
  description: "API for the period tracking app 'Cyla'"
  version: 0.1.0
  title: "Cyla App API"
servers:
  - url: "http://localhost:5000"
    description: "DEV server"
security:
  # By default, all endpoints are protected. There are some exceptions, like user sign up.
  - bearerJWTAuth: []
paths:
  /user:
    post:
      # No authorization for this endpoint needed
      security: []
      tags:
        - user
      description: Create a new user
      operationId: createUser
      requestBody:
        description: New user to create
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
      responses:
        "200":
          description: User created
          content:
            text/plain:
              schema:
                $ref: "#/components/schemas/Id"
        "500":
          description: Error when creating user
  /user/{userId}:
    get:
      tags:
        - user
      description: Get a single user
      operationId: getUserById
      parameters:
        - $ref: "#/components/parameters/userId"
      responses:
        "200":
          description: User found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        "404":
          $ref: "#/components/responses/UserNotFound"
        "500":
          description: Error when retrieving user

    put:
      tags:
        - user
      description: Update an user
      operationId: updateUser
      parameters:
        - $ref: "#/components/parameters/userId"
      requestBody:
        description: Updated user
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
      responses:
        "200":
          description: User updated successfully
        "400":
          description: Error in request
        "404":
          $ref: "#/components/responses/UserNotFound"
        "500":
          description: Error when updating user
  /user/{userId}/restore:
    get:
      tags:
        - user
      description: Get key backup for user
      operationId: getRestoreData
      parameters:
        - $ref: "#/components/parameters/userId"
      responses:
        "200":
          description: Backup information found
          content:
            text/plain:
              schema:
                $ref: "#/components/schemas/EncryptedAttribute"
        "404":
          $ref: "#/components/responses/UserNotFound"
  /day/{userId}:
    post:
      tags:
        - day
      description: Adds a day for an user or updates it
      operationId: modifyDayEntry
      parameters:
        - $ref: "#/components/parameters/userId"
      requestBody:
        description: New day to create
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Day"
      responses:
        "200":
          description: Day succesfully created
        "404":
          description: User not found
        "500":
          description: Error when creating day
  /day/{userId}/byDate:
    get:
      tags:
        - day
      description: Get the day from user at date
      operationId: getDaysByUserIdAndDate
      parameters:
        - $ref: "#/components/parameters/userId"
        - name: date
          in: query
          description: date(s) of the entries to get
          explode: true
          style: form
          schema:
            type: array
            items:
              $ref: "#/components/schemas/DayDate"
      responses:
        "200":
          $ref: "#/components/responses/DaysFound"
        "404":
          description: Day entry with date not found
        "500":
          description: Error when retrieving days
  /day/{userId}/byRange:
    get:
      tags:
        - day
      description: Get a range of dates from user. If not provided, end defaults to start. Both dates are inclusive.
      operationId: getDayByUserAndRange
      parameters:
        - $ref: "#/components/parameters/userId"
        - name: startDate
          in: query
          description: start date
          required: true
          schema:
            $ref: "#/components/schemas/DayDate"
        - name: endDate
          in: query
          description: end date
          required: false
          schema:
            $ref: "#/components/schemas/DayDate"
      responses:
        "200":
          $ref: "#/components/responses/DaysFound"
        "500":
          description: Error when retrieving days
components:
  parameters:
    userId:
      description: Path parameter for id of user to return
      in: path
      name: userId
      required: true
      schema:
        $ref: "#/components/schemas/Id"
    date:
      description: Query parameter for date
      name: date
      in: query
      required: true
      schema:
        $ref: "#/components/schemas/DayDate"
  responses:
    DaysFound:
      description: (Empty) list of days found
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: "#/components/schemas/Day"
    UserNotFound:
      description: Error about missing user
      content:
        application/json:
          schema:
            type: string
    Unauthorized:
      description: Access token missing or invalid
      content:
        text/plain:
          schema:
            type: string
            description: Error message
  schemas:
    EncryptedAttribute:
      title: encryptedAttribute
      type: string
      format: byte
    DayDate:
      title: date
      description:  ISO-8601-formatted date for an day entry. Only the date, no time is given.
      type: string
      format: date
    Id:
      title: id
      type: string
      description: UUID
    User:
      title: user
      type: object
      description: An User of the app
      properties:
        id:
          $ref: "#/components/schemas/Id"
        username:
          title: username
          type: string
          description: unique username. Chosen by the user upon account creation
        user_key_backup:
          $ref: "#/components/schemas/EncryptedAttribute"
        auth_key:
          $ref: '#/components/schemas/EncryptedAttribute'
    Day:
      title: day
      type: object
      description: A Day entry
      properties:
        day_key:
          format: byte
          type: string
          description: Day key used to encrypt sensitive information for the day.
        version:
          type: integer
        date:
          $ref: "#/components/schemas/DayDate"
        dayInfo:
          $ref: "#/components/schemas/EncryptedAttribute"
      required:
        - version
        - dayInfo
        - date
  securitySchemes:
    bearerJWTAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
