/*
 * Cyla App API
 *
 * API for the period tracking app 'Cyla'
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package server

import (
	"context"
	"errors"
	"net/http"
)

// CervicalApiService is a service that implents the logic for the CervicalApiServicer
// This service should implement the business logic for every endpoint for the CervicalApi API.
// Include any external packages or services that will be required by this service.
type CervicalApiService struct {
}

// NewCervicalApiService creates a default api service
func NewCervicalApiService() CervicalApiServicer {
	return &CervicalApiService{}
}

// GetCervicalByDate -
func (s *CervicalApiService) GetCervicalByDate(ctx context.Context, userId int64, date string) (ImplResponse, error) {
	// TODO - update GetCervicalByDate with the required logic for this service method.
	// Add api_cervical_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, CervicalMucus{}) or use other options such as http.Ok ...
	//return Response(200, CervicalMucus{}), nil

	//TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	//return Response(404, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetCervicalByDate method not implemented")
}
