/*
 * Cyla App API
 *
 * API for the period tracking app 'Cyla'
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package server

import (
	"context"
	"errors"
	"net/http"
)

// DayApiService is a service that implents the logic for the DayApiServicer
// This service should implement the business logic for every endpoint for the DayApi API.
// Include any external packages or services that will be required by this service.
type DayApiService struct {
}

// NewDayApiService creates a default api service
func NewDayApiService() DayApiServicer {
	return &DayApiService{}
}

// CreateDayEntry -
func (s *DayApiService) CreateDayEntry(ctx context.Context, userId string, day Day) (ImplResponse, error) {
	//TODO Server-error vs client-error
	err := DBConnection.CreateDayEntry(ctx, userId, day)
	if err != nil {
		return Response(404, ""), err
	}
	return Response(200, "Ok"), nil
}

// GetDayByUserAndRange -
func (s *DayApiService) GetDayByUserAndRange(ctx context.Context, userId string, startDate string, endDate string) (ImplResponse, error) {
	// TODO - update GetDayByUserAndRange with the required logic for this service method.
	// Add api_day_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, []Day{}) or use other options such as http.Ok ...
	//return Response(200, []Day{}), nil

	//TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	//return Response(404, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetDayByUserAndRange method not implemented")
}

// GetDaysByUserIdAndDate -
func (s *DayApiService) GetDaysByUserIdAndDate(ctx context.Context, userId string, date []string) (ImplResponse, error) {
	//TODO Server-error vs client-error
	days, err := DBConnection.GetDaysByUserIdAndDate(ctx, userId, date)
	if err != nil {
		return Response(404, []Day{}), err
	}

	return Response(200, days), nil
}

// UpdateDayEntry -
func (s *DayApiService) UpdateDayEntry(ctx context.Context, userId string, day Day) (ImplResponse, error) {
	// TODO - update UpdateDayEntry with the required logic for this service method.
	// Add api_day_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, {}) or use other options such as http.Ok ...
	//return Response(200, nil),nil

	//TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	//return Response(404, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("UpdateDayEntry method not implemented")
}
