/*
 * Cyla App API
 *
 * API for the period tracking app 'Cyla'
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package server

import (
	"context"
	"errors"
	"net/http"
)

// BleedingApiService is a service that implents the logic for the BleedingApiServicer
// This service should implement the business logic for every endpoint for the BleedingApi API.
// Include any external packages or services that will be required by this service.
type BleedingApiService struct {
}

// NewBleedingApiService creates a default api service
func NewBleedingApiService() BleedingApiServicer {
	return &BleedingApiService{}
}

// GetBleedingByDate -
func (s *BleedingApiService) GetBleedingByDate(ctx context.Context, userId int64, date string) (ImplResponse, error) {
	// TODO - update GetBleedingByDate with the required logic for this service method.
	// Add api_bleeding_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, Bleeding{}) or use other options such as http.Ok ...
	//return Response(200, Bleeding{}), nil

	//TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	//return Response(404, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetBleedingByDate method not implemented")
}
