/*
 * Cyla App API
 *
 * API for the period tracking app 'Cyla'
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package server

import (
	"context"
	"errors"
	"net/http"
)

// ActivityApiService is a service that implents the logic for the ActivityApiServicer
// This service should implement the business logic for every endpoint for the ActivityApi API.
// Include any external packages or services that will be required by this service.
type ActivityApiService struct {
}

// NewActivityApiService creates a default api service
func NewActivityApiService() ActivityApiServicer {
	return &ActivityApiService{}
}

// GetSexActivityByDate -
func (s *ActivityApiService) GetSexActivityByDate(ctx context.Context, userId string, date string) (ImplResponse, error) {
	// TODO - update GetSexActivityByDate with the required logic for this service method.
	// Add api_activity_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, SexualActivity{}) or use other options such as http.Ok ...
	//return Response(200, SexualActivity{}), nil

	//TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	//return Response(404, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetSexActivityByDate method not implemented")
}
