/*
 * Cyla App API
 *
 * API for the period tracking app 'Cyla'
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package server

import (
	"context"
	"errors"
	"net/http"
)

// MoodApiService is a service that implents the logic for the MoodApiServicer
// This service should implement the business logic for every endpoint for the MoodApi API.
// Include any external packages or services that will be required by this service.
type MoodApiService struct {
}

// NewMoodApiService creates a default api service
func NewMoodApiService() MoodApiServicer {
	return &MoodApiService{}
}

// GetMoodByDate -
func (s *MoodApiService) GetMoodByDate(ctx context.Context, userId int64, date string) (ImplResponse, error) {
	// TODO - update GetMoodByDate with the required logic for this service method.
	// Add api_mood_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, Mood{}) or use other options such as http.Ok ...
	//return Response(200, Mood{}), nil

	//TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	//return Response(404, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetMoodByDate method not implemented")
}
