/*
 * Cyla App API
 *
 * API for the period tracking app 'Cyla'
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package server

import (
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

// A StatsApiController binds http requests to an api service and writes the service results to the http response
type StatsApiController struct {
	service StatsApiServicer
}

// NewStatsApiController creates a default api controller
func NewStatsApiController(s StatsApiServicer) Router {
	return &StatsApiController{service: s}
}

// Routes returns all of the api route for the StatsApiController
func (c *StatsApiController) Routes() Routes {
	return Routes{
		{
			"GetPeriodStats",
			strings.ToUpper("Get"),
			"/stats/{userId}/periodStats",
			Authorize(c.GetPeriodStats),
		},
		{
			"GetStats",
			strings.ToUpper("Get"),
			"/stats/{userId}",
			Authorize(c.GetStats),
		},
	}
}

// GetPeriodStats -
func (c *StatsApiController) GetPeriodStats(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	userId := params["userId"]
	result, err := c.service.GetPeriodStats(r.Context(), userId)
	//If an error occured, encode the error with the status code
	if err != nil {
		EncodeJSONResponse(err.Error(), &result.Code, result.Headers, w)
		return
	}
	//If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, result.Headers, w)

}

// GetStats -
func (c *StatsApiController) GetStats(w http.ResponseWriter, r *http.Request) {
	params := mux.Vars(r)
	userId := params["userId"]
	result, err := c.service.GetStats(r.Context(), userId)
	//If an error occured, encode the error with the status code
	if err != nil {
		EncodeJSONResponse(err.Error(), &result.Code, result.Headers, w)
		return
	}
	//If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, result.Headers, w)

}
