/*
 * Cyla App API
 *
 * API for the period tracking app 'Cyla'
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package server

import (
	"context"
	"errors"
	"net/http"
)

// PainApiService is a service that implents the logic for the PainApiServicer
// This service should implement the business logic for every endpoint for the PainApi API.
// Include any external packages or services that will be required by this service.
type PainApiService struct {
}

// NewPainApiService creates a default api service
func NewPainApiService() PainApiServicer {
	return &PainApiService{}
}

// GetPainByDate -
func (s *PainApiService) GetPainByDate(ctx context.Context, userId string, date string) (ImplResponse, error) {
	// TODO - update GetPainByDate with the required logic for this service method.
	// Add api_pain_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, Pain{}) or use other options such as http.Ok ...
	//return Response(200, Pain{}), nil

	//TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	//return Response(404, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetPainByDate method not implemented")
}
