/*
 * Cyla App API
 *
 * API for the period tracking app 'Cyla'
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package server

import (
	"context"
	"errors"
	"net/http"
)

// DesireApiService is a service that implents the logic for the DesireApiServicer
// This service should implement the business logic for every endpoint for the DesireApi API.
// Include any external packages or services that will be required by this service.
type DesireApiService struct {
}

// NewDesireApiService creates a default api service
func NewDesireApiService() DesireApiServicer {
	return &DesireApiService{}
}

// GetSexDesireByDate -
func (s *DesireApiService) GetSexDesireByDate(ctx context.Context, userId string, date string) (ImplResponse, error) {
	// TODO - update GetSexDesireByDate with the required logic for this service method.
	// Add api_desire_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, SexualDesire{}) or use other options such as http.Ok ...
	//return Response(200, SexualDesire{}), nil

	//TODO: Uncomment the next line to return response Response(404, {}) or use other options such as http.Ok ...
	//return Response(404, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetSexDesireByDate method not implemented")
}
