/*
 * Cyla App API
 *
 * API for the period tracking app 'Cyla'
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package server

import (
	"context"
)

// DayApiService is a service that implents the logic for the DayApiServicer
// This service should implement the business logic for every endpoint for the DayApi API.
// Include any external packages or services that will be required by this service.
type DayApiService struct {
}

// NewDayApiService creates a default api service
func NewDayApiService() DayApiServicer {
	return &DayApiService{}
}

// GetDayByUserAndRange -
func (s *DayApiService) GetDayByUserAndRange(ctx context.Context, userId string, startDate string, endDate string) (response ImplResponse, err error) {
	ret, err := DBConnection.GetDayByUserAndRange(ctx, userId, startDate, endDate)
	response, err = httpResponseWithBody(ret, err)
	if response.Code == 200 {
		response.Headers = []Header{{Name: "Cache-Control", Value: "max-age=86400"}}
	}
	return
}

// GetDaysByUserIdAndDate -
func (s *DayApiService) GetDaysByUserIdAndDate(ctx context.Context, userId string, date []string) (response ImplResponse, err error) {
	ret, err := DBConnection.GetDaysByUserIdAndDate(ctx, userId, date)
	response, err = httpResponseWithBody(ret, err)
	if response.Code == 200 {
		response.Headers = []Header{{Name: "Cache-Control", Value: "max-age=86400"}}
	}
	return
}

// ModifyDayEntry -
func (s *DayApiService) ModifyDayEntry(ctx context.Context, userId string, day Day) (response ImplResponse, err error) {
	err = DBConnection.ModifyDayEntry(ctx, userId, day)
	response, err = httpResponse(err)
	return
}

// ModifyDayEntryWithStats -
func (s *DayApiService) ModifyDayEntryWithStats(ctx context.Context, userId string, dayStatsUpdate DayStatsUpdate) (response ImplResponse, err error) {
	err = DBConnection.ModifyDayEntryWithStats(ctx, userId, dayStatsUpdate)
	response, err = httpResponse(err)
	return
}
