/*
 * Cyla App API
 *
 * API for the period tracking app 'Cyla'
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package server

import (
	"context"
)

// ShareApiService is a service that implents the logic for the ShareApiServicer
// This service should implement the business logic for every endpoint for the ShareApi API.
// Include any external packages or services that will be required by this service.
type ShareApiService struct {
}

// NewShareApiService creates a default api service
func NewShareApiService() ShareApiServicer {
	return &ShareApiService{}
}

// GetShares -
func (s *ShareApiService) GetShares(ctx context.Context, userId string) (response ImplResponse, err error) {
	ret, err := DBConnection.GetShares(ctx, userId)
	response, err = httpResponseWithBody(ret, err)
	return
}

// ShareAuth -
func (s *ShareApiService) ShareAuth(ctx context.Context, shareId string, sharedPwdDto SharedPwdDto) (response ImplResponse, err error) {
	ret, err := DBConnection.ShareAuth(ctx, shareId, sharedPwdDto)
	response, err = httpResponseWithBody(ret, err)
	return
}

// ShareDays -
func (s *ShareApiService) ShareDays(ctx context.Context, userId string, shareInfoUpload ShareInfoUpload) (response ImplResponse, err error) {
	ret, err := DBConnection.ShareDays(ctx, userId, shareInfoUpload)
	response, err = httpResponseWithBody(ret, err)
	return
}
