/*
 * Cyla App API
 *
 * API for the period tracking app 'Cyla'
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package server

import (
	"context"
)

// ShareDayApiService is a service that implents the logic for the ShareDayApiServicer
// This service should implement the business logic for every endpoint for the ShareDayApi API.
// Include any external packages or services that will be required by this service.
type ShareDayApiService struct {
}

// NewShareDayApiService creates a default api service
func NewShareDayApiService() ShareDayApiServicer {
	return &ShareDayApiService{}
}

// ShareGetDayByUserAndRange -
func (s *ShareDayApiService) ShareGetDayByUserAndRange(ctx context.Context, shareId string, startDate string, endDate string) (response ImplResponse, err error) {
	ret, err := DBConnection.ShareGetDayByUserAndRange(ctx, shareId, startDate, endDate)
	response, err = httpResponseWithBody(ret, err)
	if response.Code == 200 {
		response.Headers = []Header{{Name: "Cache-Control", Value: "max-age=86400"}}
	}
	return
}

// ShareGetDaysByUserIdAndDate -
func (s *ShareDayApiService) ShareGetDaysByUserIdAndDate(ctx context.Context, shareId string, date []string) (response ImplResponse, err error) {
	ret, err := DBConnection.ShareGetDaysByUserIdAndDate(ctx, shareId, date)
	response, err = httpResponseWithBody(ret, err)
	if response.Code == 200 {
		response.Headers = []Header{{Name: "Cache-Control", Value: "max-age=86400"}}
	}
	return
}
