/*
 * Cyla App API
 *
 * API for the period tracking app 'Cyla'
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package server

import (
	"context"
)

// StatsApiService is a service that implents the logic for the StatsApiServicer
// This service should implement the business logic for every endpoint for the StatsApi API.
// Include any external packages or services that will be required by this service.
type StatsApiService struct {
}

// NewStatsApiService creates a default api service
func NewStatsApiService() StatsApiServicer {
	return &StatsApiService{}
}

// GetPeriodStats -
func (s *StatsApiService) GetPeriodStats(ctx context.Context, userId string) (response ImplResponse, err error) {
	ret, err := DBConnection.GetPeriodStats(ctx, userId)
	response, err = httpResponseWithBody(ret, err)
	if response.Code == 200 {
		response.Headers = []Header{{Name: "Cache-Control", Value: "max-age=86400"}}
	}
	return
}

// GetStats -
func (s *StatsApiService) GetStats(ctx context.Context, userId string) (response ImplResponse, err error) {
	ret, err := DBConnection.GetStats(ctx, userId)
	response, err = httpResponseWithBody(ret, err)
	if response.Code == 200 {
		response.Headers = []Header{{Name: "Cache-Control", Value: "max-age=86400"}}
	}
	return
}
