/*
 * Cyla App API
 *
 * API for the period tracking app 'Cyla'
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package server

type Header struct {
	Name  string
	Value string
}

//Implementation response defines an error code with the associated body
type ImplResponse struct {
	Headers []Header
	Code    int
	Body    interface{}
}
