/*
 * Cyla App API
 *
 * API for the period tracking app 'Cyla'
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package server

// DayStatsUpdate - DTO for updating a day and relevant stats in one server call
type DayStatsUpdate struct {
	Day Day `json:"day,omitempty" mapstructure:"Day"`

	Stats Stats `json:"stats,omitempty" mapstructure:"Stats"`
}

func GetDayStatsUpdateDayName() string {
	return "Day"
}
func GetDayStatsUpdateStatsName() string {
	return "Stats"
}
