/*
 * Cyla App API
 *
 * API for the period tracking app 'Cyla'
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package server

// Temperature - Temperature information for a day
type Temperature struct {

	// UUID
	Id string `json:"id,omitempty" mapstructure:"Id"`

	Value string `json:"value,omitempty" mapstructure:"Value"`

	Timestamp string `json:"timestamp,omitempty" mapstructure:"Timestamp"`

	Note string `json:"note,omitempty" mapstructure:"Note"`

	Exclude string `json:"exclude,omitempty" mapstructure:"Exclude"`
}
