/*
 * Cyla App API
 *
 * API for the period tracking app 'Cyla'
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package server

// UserCreatedResponse - Information related to user signup. Includes the UUID of the new user and a fresh JWT for further requests.
type UserCreatedResponse struct {

	// UUID
	UserId string `json:"userId,omitempty" mapstructure:"UserId"`

	// Fresh JWT for authentication
	Jwt string `json:"jwt,omitempty" mapstructure:"Jwt"`
}

func GetUserCreatedResponseUserIdName() string {
	return "UserId"
}
func GetUserCreatedResponseJwtName() string {
	return "Jwt"
}
