/*
 * Cyla App API
 *
 * API for the period tracking app 'Cyla'
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package server

// CervicalMucus - Cervical Mucus information for a day
type CervicalMucus struct {

	// UUID
	Id string `json:"id,omitempty" mapstructure:"Id"`

	Feeling EncryptedAttribute `json:"feeling,omitempty" mapstructure:"Feeling"`

	Texture EncryptedAttribute `json:"texture,omitempty" mapstructure:"Texture"`

	Exclude EncryptedAttribute `json:"exclude,omitempty" mapstructure:"Exclude"`
}

func (s *CervicalMucus) GetIdFieldName() string {
	return "Id"
}
func (s *CervicalMucus) GetFeelingFieldName() string {
	return "Feeling"
}
func (s *CervicalMucus) GetTextureFieldName() string {
	return "Texture"
}
func (s *CervicalMucus) GetExcludeFieldName() string {
	return "Exclude"
}
