/*
 * Cyla App API
 *
 * API for the period tracking app 'Cyla'
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package server

// UserStats - Data structures used by Cyla to compute stats like average Period length.
type UserStats struct {
	PeriodStats Statistic `json:"periodStats,omitempty" mapstructure:"PeriodStats"`
}

func GetUserStatsPeriodStatsName() string {
	return "PeriodStats"
}
