/*
 * Cyla App API
 *
 * API for the period tracking app 'Cyla'
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package server

// ChangePassphraseDto - Information for requesting a passphrase change for a user
type ChangePassphraseDto struct {
	OldAuthKey EncryptedAttribute `json:"oldAuthKey,omitempty" mapstructure:"OldAuthKey"`

	NewEncryptedUserKey EncryptedAttribute `json:"newEncryptedUserKey,omitempty" mapstructure:"NewEncryptedUserKey"`

	NewAuthKey EncryptedAttribute `json:"newAuthKey,omitempty" mapstructure:"NewAuthKey"`
}

func GetChangePassphraseDtoOldAuthKeyName() string {
	return "OldAuthKey"
}
func GetChangePassphraseDtoNewEncryptedUserKeyName() string {
	return "NewEncryptedUserKey"
}
func GetChangePassphraseDtoNewAuthKeyName() string {
	return "NewAuthKey"
}
