/*
 * Cyla App API
 *
 * API for the period tracking app 'Cyla'
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package server

// Statistic - Encrypted data structure for a single stat.
type Statistic struct {
	Value EncryptedAttribute `json:"value,omitempty" mapstructure:"Value"`

	// Hash value for the previous version for this user's stat. For conflict detection.
	PrevHashValue string `json:"prevHashValue,omitempty" mapstructure:"PrevHashValue"`
}

func GetStatisticValueName() string {
	return "Value"
}
func GetStatisticPrevHashValueName() string {
	return "PrevHashValue"
}
