/*
 * Cyla App API
 *
 * API for the period tracking app 'Cyla'
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package server

// User - An User of the app
type User struct {

	// UUID
	Id string `json:"id,omitempty" mapstructure:"Id"`

	// unique username. Chosen by the user upon account creation
	Username string `json:"username,omitempty" mapstructure:"Username"`

	UserKeyBackup EncryptedAttribute `json:"user_key_backup,omitempty" mapstructure:"UserKeyBackup"`

	AuthKey string `json:"auth_key,omitempty" mapstructure:"AuthKey"`
}

func GetUserIdName() string {
	return "Id"
}
func GetUserUsernameName() string {
	return "Username"
}
func GetUserUserKeyBackupName() string {
	return "UserKeyBackup"
}
func GetUserAuthKeyName() string {
	return "AuthKey"
}
