/*
 * Cyla App API
 *
 * API for the period tracking app 'Cyla'
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package server

type SuccessfulShareAuthData struct {

	// Fresh JWT for share authentication
	Jwt string `json:"jwt,omitempty" mapstructure:"Jwt"`

	ShareKey EncryptedAttribute `json:"shareKey,omitempty" mapstructure:"ShareKey"`
}

func GetSuccessfulShareAuthDataJwtName() string {
	return "Jwt"
}
func GetSuccessfulShareAuthDataShareKeyName() string {
	return "ShareKey"
}
