/*
 * Cyla App API
 *
 * API for the period tracking app 'Cyla'
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package server

type SharedPwdDto struct {
	HashedPwd string `json:"hashedPwd" mapstructure:"HashedPwd"`
}

func GetSharedPwdDtoHashedPwdName() string {
	return "HashedPwd"
}
