---
--- Generated by Luanalysis
--- Created by Besitzer.
--- DateTime: 16.01.2021 15:29
---
local uuid = redis.call("GET", KEYS[1])
if uuid then
    local backupKey = redis.call("HGET", KEYS[2] .. ":" .. uuid, ARGV[1])
    local authKey = redis.call("HGET", KEYS[2] .. ":" .. uuid, ARGV[2])
    return {uuid, backupKey, authKey}
else
    return nil
end
