---
--- Generated by Luanalysis
--- Created by Besitzer.
--- DateTime: 26.01.2021 15:18
---
local isUserExist = redis.call('EXISTS', KEYS[1])
if isUserExist == 0 then
    --- TODO: return error replies instead of codes
    return 0
else
    redis.call('HSET', KEYS[2], unpack(ARGV))
    return 1
end
