---
--- Generated by Luanalysis
--- Created by Besitzer.
--- DateTime: 09.12.2020 16:19
---
local dates = redis.call("ZRANGEBYLEX", KEYS[1], "[" .. ARGV[1], "[" .. ARGV[2])
local allDays = {}
for _, date in ipairs(dates) do
    table.insert(allDays, redis.call("HGETALL", KEYS[1] .. ":" .. date))
end
return allDays

